import { z } from "zod";

import logger from "../../lib/logger";
import { PrintifyRequestError } from "./client.server";
import { getPrintifyIntegrationWithToken } from "./integration.server";
import { decryptPrintifyToken } from "./token-encryption.server";
import {
  PRINTIFY_BASE_URL,
  assertPrintifyOk,
  fetchPrintify,
} from "./request.server";

export type PrintifyVariantSelection = {
  id: number;
  price: number;
  isEnabled?: boolean;
};

export type PrintifyPrintAreaImage = {
  url: string;
  position?: string;
  x?: number;
  y?: number;
  scale?: number;
  angle?: number;
};

export type PrintifyTempProductResult = {
  productId: string;
  mockupUrls: string[];
};

const DEFAULT_PREVIEW_IMAGE_SCALE = 1;

const printifyUploadResponseSchema = z.object({
  id: z.union([z.string(), z.number()]),
});

const printifyProductResponseSchema = z.object({
  id: z.union([z.string(), z.number()]),
  images: z
    .array(
      z.object({
        src: z.string(),
        type: z.string().optional(),
      }),
    )
    .optional(),
});

const resolveFileName = (imageUrl: string): string => {
  try {
    const url = new URL(imageUrl);
    const pathname = url.pathname.split("/").pop();
    if (pathname && pathname.includes(".")) {
      return pathname;
    }
  } catch {
    // Ignore URL parsing failures.
  }

  return `preview-${Date.now()}.png`;
};

const uploadPrintifyImage = async (
  token: string,
  imageUrl: string,
): Promise<string> => {
  const response = await fetchPrintify(
    `${PRINTIFY_BASE_URL}/uploads/images.json`,
    token,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        file_name: resolveFileName(imageUrl),
        url: imageUrl,
      }),
    },
  );

  await assertPrintifyOk(response, "Unable to upload image to Printify.");

  const payload = (await response.json()) as unknown;
  const parsed = printifyUploadResponseSchema.safeParse(payload);
  if (!parsed.success) {
    throw new PrintifyRequestError(
      "unexpected_response",
      "Printify upload response was invalid.",
    );
  }

  return String(parsed.data.id);
};

const extractMockupUrls = (
  images: { src: string; type?: string }[],
): string[] => {
  if (!images.length) {
    return [];
  }

  const mockups = images.filter((image) => image.type === "mockup");
  const source = mockups.length ? mockups : images;
  return source.map((image) => image.src);
};

export const createTempProduct = async (
  shopId: string,
  blueprintId: number,
  printProviderId: number,
  variants: PrintifyVariantSelection[],
  printAreaImage: PrintifyPrintAreaImage,
): Promise<PrintifyTempProductResult> => {
  const integration = await getPrintifyIntegrationWithToken(shopId);
  if (!integration) {
    throw new PrintifyRequestError(
      "unexpected_response",
      "Printify integration not configured for this shop.",
    );
  }

  if (variants.length === 0) {
    throw new PrintifyRequestError(
      "printify_no_variants",
      "At least one Printify variant is required.",
    );
  }

  const token = decryptPrintifyToken(integration.encryptedToken);
  const uploadId = await uploadPrintifyImage(token, printAreaImage.url);
  const variantIds = variants.map((variant) => variant.id);

  const response = await fetchPrintify(
    `${PRINTIFY_BASE_URL}/shops/${integration.printifyShopId}/products.json`,
    token,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        title: `Preview ${new Date().toISOString()}`,
        description: "Temporary preview product generated by Personalize.",
        blueprint_id: blueprintId,
        print_provider_id: printProviderId,
        variants: variants.map((variant) => ({
          id: variant.id,
          price: variant.price,
          is_enabled: variant.isEnabled ?? true,
        })),
        print_areas: [
          {
            variant_ids: variantIds,
            placeholders: [
              {
                position: printAreaImage.position ?? "front",
                images: [
                  {
                    id: uploadId,
                    x: printAreaImage.x ?? 0.5,
                    y: printAreaImage.y ?? 0.5,
                    scale: printAreaImage.scale ?? DEFAULT_PREVIEW_IMAGE_SCALE,
                    angle: printAreaImage.angle ?? 0,
                  },
                ],
              },
            ],
          },
        ],
      }),
    },
  );

  await assertPrintifyOk(
    response,
    "Unable to create temporary Printify product.",
  );

  const payload = (await response.json()) as unknown;
  const parsed = printifyProductResponseSchema.safeParse(payload);
  if (!parsed.success) {
    throw new PrintifyRequestError(
      "printify_invalid_product_response",
      "Printify product response was invalid.",
    );
  }

  const productId = String(parsed.data.id);

  const detailsResponse = await fetchPrintify(
    `${PRINTIFY_BASE_URL}/shops/${integration.printifyShopId}/products/${productId}.json`,
    token,
    { method: "GET" },
  );

  await assertPrintifyOk(detailsResponse, "Unable to fetch Printify mockups.");

  const detailsPayload = (await detailsResponse.json()) as unknown;
  const detailsParsed = printifyProductResponseSchema.safeParse(detailsPayload);
  if (!detailsParsed.success) {
    throw new PrintifyRequestError(
      "printify_invalid_product_details",
      "Printify product details were invalid.",
    );
  }

  const mockupUrls = extractMockupUrls(detailsParsed.data.images ?? []);

  logger.info(
    {
      shop_id: shopId,
      printify_shop_id: integration.printifyShopId,
      printify_product_id: productId,
      mockup_count: mockupUrls.length,
    },
    "Created temporary Printify product",
  );

  return { productId, mockupUrls };
};

export const deleteProduct = async (
  shopId: string,
  productId: string,
): Promise<void> => {
  const integration = await getPrintifyIntegrationWithToken(shopId);
  if (!integration) {
    throw new PrintifyRequestError(
      "unexpected_response",
      "Printify integration not configured for this shop.",
    );
  }

  const token = decryptPrintifyToken(integration.encryptedToken);

  const response = await fetchPrintify(
    `${PRINTIFY_BASE_URL}/shops/${integration.printifyShopId}/products/${productId}.json`,
    token,
    { method: "DELETE" },
  );

  await assertPrintifyOk(
    response,
    "Unable to delete temporary Printify product.",
  );

  logger.info(
    {
      shop_id: shopId,
      printify_shop_id: integration.printifyShopId,
      printify_product_id: productId,
    },
    "Deleted temporary Printify product",
  );
};
